# Generated by Django 4.1.7 on 2023-05-17 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('collection', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('FT', 'Family or Bachelor Flat'), ('FF', 'Family Flat'), ('MB', 'Male Flat'), ('FB', 'Female Flat'), ('MM', 'Male Mess'), ('FM', 'Female Mess')], max_length=2)),
                ('kitchen', models.PositiveSmallIntegerField(choices=[(0, 'Not Available'), (1, 'Shared'), (2, 'Attached')])),
                ('washroom', models.PositiveSmallIntegerField(choices=[(1, 'Shared'), (2, 'Attached')])),
            ],
        ),
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.PositiveSmallIntegerField(choices=[(2, 'REJECT'), (1, 'REQUEST'), (0, 'RESOLVE')])),
                ('AssetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenureApp.assets')),
            ],
        ),
    ]
